title: Syafitri Rihandini # your name (or website title) here
logo: "/images/foto.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mathematics Student at Airlangga University
  <br><br>
  Independent Study at Zenius Education
  <br><br>
  Data Sciencetist
  <br><br>
  <a href="https://www.linkedin.com/in/syafitri-rihandini-1a342a20a">View My LinkedIn Profil</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
